[env:esp32-s3-rgb-matrix]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 32MB
board_upload.flash_size = 32MB

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@3.0.14
    adafruit/Adafruit GFX Library
